### ISSUE TITLE
You should have more basic sorts of projects which are more suitable for beginner-ish learners.

### ISSUE THREAD

**Issue by sbeve72** [androiddevnotes/awesome-android-learning-resources#17]
All the projects in this repo are awesome and they seem really promising. However I do have one problem, all of these projects are just way too high level. For a person like me, I don't know how MVVM works or RxJava works and these projects use those kinds of things which are way out of league for me. And sure as hell I should learn those things but right now I want to see the usage of more basic stuff. Either the use of MVVM in more basic and simple ways, or apps that don't use the stuff I don't understand. Like for example a basic app that implements the androix and navigation components. THese are the things beginners might need to see the best practices of instead very advanced features like RxJava and Architectural Patterns. I would like to see apps implement the latest Jetpack libraries and the material design library with best practices. These things are not too high level but they are also very important to learn.

**Comment by androiddevnotes** [comment]
@sbeve72 Good point. I get what you mean. I think I will make a new repo focused on Beginners including all the Tech Stack you mentioned.

If you want to be updated on the progress, please join the Discord server: Invite link - https://discord.gg/vBnEhuC

Thank you for your suggestions.

**Comment by sbeve72** [comment]
has this been implemented yet?
