### ISSUE TITLE
Remove Android Security empty link

### ISSUE THREAD

**Issue by zeusalmighty717** [androiddevnotes/awesome-android-learning-resources#48]
- At Line 55 there is an empty link for ```Android security```.
- At this time only 'The Mobile Security Testing Guide (MSTG)' is related to security and doesn't make sense to keep it in a separate section.

**Comment by zeusalmighty717** [comment]
I can do a quick PR if get a go-ahead.

**Comment by androiddevnotes** [comment]
> I can do a quick PR if get a go-ahead.

Yes, send a PR! Thank you for noticing.
